In [214]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
#para graficar el arbol de desicion
import numpy as np
from sklearn.metrics import confusion_matrix

In [215]:
data=pd.read_csv("datasetVideoGames2.csv")
data.columns

Index(['title', 'console', 'alcohol_reference', 'animated_blood', 'blood',
       'blood_and_gore', 'cartoon_violence', 'crude_humor', 'drug_reference',
       'fantasy_violence', 'intense_violence', 'language', 'lyrics',
       'mature_humor', 'mild_blood', 'mild_cartoon_violence',
       'mild_fantasy_violence', 'mild_language', 'mild_lyrics',
       'mild_suggestive_themes', 'mild_violence', 'no_descriptors', 'nudity',
       'partial_nudity', 'sexual_content', 'sexual_themes',
       'simulated_gambling', 'strong_janguage', 'strong_sexual_content',
       'suggestive_themes', 'use_of_alcohol', 'use_of_drugs_and_alcohol',
       'violence', 'esrb_rating'],
      dtype='object')

In [216]:
variables_predictoras=data[['console', 'alcohol_reference', 'animated_blood', 'blood',
       'blood_and_gore', 'cartoon_violence', 'crude_humor', 'drug_reference',
       'fantasy_violence', 'intense_violence', 'language', 'lyrics',
       'mature_humor', 'mild_blood', 'mild_cartoon_violence',
       'mild_fantasy_violence', 'mild_language', 'mild_lyrics',
       'mild_suggestive_themes', 'mild_violence', 'no_descriptors', 'nudity',
       'partial_nudity', 'sexual_content', 'sexual_themes',
       'simulated_gambling', 'strong_janguage', 'strong_sexual_content',
       'suggestive_themes', 'use_of_alcohol', 'use_of_drugs_and_alcohol',
       'violence']]
variable_a_predecir=data.esrb_rating
variable_a_predecir.unique()#esta linea de codigo la usamos para obtener las salidas unicas del dataset

array(['E', 'ET', 'M', 'T'], dtype=object)

In [217]:
#etiquetamos las predictoras y los objetivos
etiquetas_predictoras=['console', 'alcohol_reference', 'animated_blood', 'blood',
       'blood_and_gore', 'cartoon_violence', 'crude_humor', 'drug_reference',
       'fantasy_violence', 'intense_violence', 'language', 'lyrics',
       'mature_humor', 'mild_blood', 'mild_cartoon_violence',
       'mild_fantasy_violence', 'mild_language', 'mild_lyrics',
       'mild_suggestive_themes', 'mild_violence', 'no_descriptors', 'nudity',
       'partial_nudity', 'sexual_content', 'sexual_themes',
       'simulated_gambling', 'strong_janguage', 'strong_sexual_content',
       'suggestive_themes', 'use_of_alcohol', 'use_of_drugs_and_alcohol',
       'violence']
etiquetas_objetivos=["E","ET","M","T"]

In [218]:
a=[]
b=[]
c=[]
d=[]
for i in range(11):
    x_entrenamiento,x_prueva,y_entrenamiento,y_prueva=train_test_split(variables_predictoras,variable_a_predecir,test_size=0.2)
    #aqui entrenamos al arbol
    arbol=DecisionTreeClassifier(criterion="entropy")
    arbol.fit(x_entrenamiento,y_entrenamiento)
    prediccion=arbol.predict(x_prueva)
    #verifica que tan segura es la prediccion del arbol, mientras mas cerca a 1 mucho mejor sera el clasificador que estamos usando
    a.append(arbol.score(x_prueva,y_prueva))
    b.append(arbol.score(x_entrenamiento,y_entrenamiento))
    c.append(1-arbol.score(x_prueva,y_prueva))
    d.append(1-arbol.score(x_entrenamiento,y_entrenamiento))
#muestra los indices de predicion del arbol
print("confiabilidad de los datos de prueva===========>  {} %".format(sum(a)/10))
print("error de los datos de prueva===================>  {} %".format(sum(c)/10))
print("confiabilidad de los datos de entrenamiento====>  {} %".format(sum(b)/10))#es mas que 1, entonces hay que hacer sobreajuste
print("error de los datos de entrenamiento============>  {} %".format(sum(d)/10))

confiabilidad de los datos de prueva===========>  0.9889999999999999 %
error de los datos de prueva===================>  0.11099999999999999 %
confiabilidad de los datos de entrenamiento====>  1.037375 %
error de los datos de entrenamiento============>  0.062625 %


In [219]:
print(confusion_matrix(y_prueva,prediccion))

[[42  0  0  0]
 [ 0 29  0  1]
 [ 0  0 53  2]
 [ 0 11  2 60]]


In [220]:
data.describe()

console  alcohol_reference  animated_blood        blood  \
count  1000.000000        1000.000000     1000.000000  1000.000000   
mean      0.538000           0.054000        0.014000     0.172000   
std       0.498803           0.226131        0.117549     0.377569   
min       0.000000           0.000000        0.000000     0.000000   
25%       0.000000           0.000000        0.000000     0.000000   
50%       1.000000           0.000000        0.000000     0.000000   
75%       1.000000           0.000000        0.000000     0.000000   
max       1.000000           1.000000        1.000000     1.000000   

       blood_and_gore  cartoon_violence  crude_humor  drug_reference  \
count     1000.000000       1000.000000  1000.000000     1000.000000   
mean         0.152000          0.026000     0.051000        0.040000   
std          0.359201          0.159215     0.220108        0.196057   
min          0.000000          0.000000     0.000000        0.000000   
25%          0.000000          0.000000     0.000000        0.000000   
50%          0.000000          0.000000     0.000000        0.000000   
75%          0.000000          0.000000     0.000000        0.000000   
max          1.000000          1.000000     1.000000        1.000000   

       fantasy_violence  intense_violence  ...  partial_nudity  \
count       1000.000000       1000.000000  ...     1000.000000   
mean           0.235000          0.135000  ...        0.007000   
std            0.424211          0.341895  ...        0.083414   
min            0.000000          0.000000  ...        0.000000   
25%            0.000000          0.000000  ...        0.000000   
50%            0.000000          0.000000  ...        0.000000   
75%            0.000000          0.000000  ...        0.000000   
max            1.000000          1.000000  ...        1.000000   

       sexual_content  sexual_themes  simulated_gambling  strong_janguage  \
count     1000.000000    1000.000000         1000.000000       1000.00000   
mean         0.049000       0.052000            0.072000          0.13900   
std          0.215976       0.222138            0.258617          0.34612   
min          0.000000       0.000000            0.000000          0.00000   
25%          0.000000       0.000000            0.000000          0.00000   
50%          0.000000       0.000000            0.000000          0.00000   
75%          0.000000       0.000000            0.000000          0.00000   
max          1.000000       1.000000            1.000000          1.00000   

       strong_sexual_content  suggestive_themes  use_of_alcohol  \
count            1000.000000        1000.000000     1000.000000   
mean                0.045000           0.156000        0.014000   
std                 0.207408           0.363037        0.117549   
min                 0.000000           0.000000        0.000000   
25%                 0.000000           0.000000        0.000000   
50%                 0.000000           0.000000        0.000000   
75%                 0.000000           0.000000        0.000000   
max                 1.000000           1.000000        1.000000   

       use_of_drugs_and_alcohol     violence  
count               1000.000000  1000.000000  
mean                   0.016000     0.081000  
std                    0.125538     0.272972  
min                    0.000000     0.000000  
25%                    0.000000     0.000000  
50%                    0.000000     0.000000  
75%                    0.000000     0.000000  
max                    1.000000     1.000000  

[8 rows x 32 columns]